spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ponrenjithnarayanavadivoo/cloud-config-url
server:
    port: 8888 

